#!/usr/bin/env bash

WALLPAPERS=("Sair")
while IFS=  read -r -d $'\0'; do
    WALLPAPERS+=("$REPLY")
done < <(find $HOME/img/nord -name "*.png" -print0)

while [ "$CONFIG" != "Sair" ]; do
    CONFIG=$(printf '%s\n' "${WALLPAPERS[@]}" | dmenu -i -l 20 -p "Wallpapers: ")
    [ -z "$CONFIG" ] || [ "$CONFIG" == "Sair" ] && exit
    feh --bg-fill "$CONFIG"
done
