#!/bin/sh

timeout=$IDLE
cycle=300
stand_time=600
suspend_time=0 
off_time=1800

if [ $(xset -q | awk '/timeout:/{print $2}') -ne 0 ]; then
    notify-send -h int:transient:1 -i $HOME/.local/share/icons/dwm/gnome-lockscreen.svg "ScreenLocker" "Screen Locker Desabilitado"
    xset -dpms
    xset s 0 0
else
    notify-send -h int:transient:1 -i $HOME/.local/share/icons/dwm/gnome-lockscreen.svg "ScreenLocker" "Screen Locker Habilitado"
    xset dpms $stand_time $suspend_time $off_time
    xset s $timeout $cycle
fi
