#!/bin/sh

local secs timeout
secs=$(xset -q | awk '/timeout:/{print $2}')
timeout=120

if [ $secs -eq 0 ]; then
    notify-send -h int:transient:1 -i $HOME/.local/share/icons/dwm/gnome-lockscreen.svg "ScreenLocker" "Screen Locker Habilitado"
    xset s $timeout
else
    notify-send -h int:transient:1 -i $HOME/.local/share/icons/dwm/gnome-lockscreen.svg "ScreenLocker" "Screen Locker Desabilitado"
    xset s 0
fi
