#!/usr/bin/env bash

sink1="$(pactl list short sinks | awk '{print $2}' | head -n1)"
sink2="$(pactl list short sinks | awk '{print $2}' | tail -n1)"
current="$(pactl get-default-sink)"

if [ "$sink1" == "$current" ]; then
    pactl set-default-sink $sink2
else
    pactl set-default-sink $sink1
fi
