#!/bin/sh

selected=$(echo -e "Desligar\nSuspender\nHibernar\nReiniciar\nSair\nCancelar" | dmenu -l 6)
[ -z "$selected" ] || [ "$selected" == "Cancelar" ] && exit

confirm=$(echo -e "Sim\nNão" | dmenu -p "Tem Certeza?")
[ -z "$confirm" ] || [ "$confirm" != "Sim" ] && exit

case $selected in
  "Desligar") sudo systemctl poweroff ;;
  "Suspender") sudo systemctl suspend ;;
  "Reiniciar") sudo systemctl reboot ;;
  "Sair") killall Xorg ;;
  *) echo "Opção Inválida!" ;;
esac
